s = Shop(shopname='黄焖鸡米饭', least_price=20, deliver_fee=5, review_score=4.5, user_id_id=1)
s.save()
s = Shop(shopname='湖畔人家', least_price=15, deliver_fee=3, review_score=4.1, user_id_id=3)
s.save()
m = Merchandise(title='小份黄焖鸡', price=15, shop_id_id = 1)
m.save()
m = Merchandise(title='大份黄焖鸡', price=20, shop_id_id = 1)
m.save()
m = Merchandise(title='土豆', price=2, shop_id_id=1)
m.save()
m = Merchandise(title='金针菇', price=4, shop_id_id=1)
m.save()
m = Merchandise(title='雪碧', price=3, shop_id_id=1)
m.save()
m = Merchandise(title='黑胶猪排饭', price=3, shop_id_id=2)
m.save()
m = Merchandise(title='咖喱鸡腿饭', price=16, shop_id_id=2)
m.save()
m = Merchandise(title='牛肉炒饭', price=15, shop_id_id=2)
m.save()
m = Merchandise(title='西红柿鸡蛋盖浇饭', price=11, shop_id_id=2)
m.save()
m = Merchandise(title='猪排饭', price=14, shop_id_id=2)
m.save()
m = Merchandise(title='照烧鸡腿饭', price=18, shop_id_id=2)
m.save()
m = Merchandise(title='回锅肉盖浇饭', price=17, shop_id_id=2)
m.save()
d = datetime.now()
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,2), order_time=d, total_price=22, status=0, shop_id_id=1, user_id_id=2, address_id_id=2)
o.save()
d = datetime.now()
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,4), order_time=d, total_price=20, status=0, shop_id_id=2, user_id_id=4, address_id_id=4)
o.save()
d = datetime.now()
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,4), order_time=d, total_price=24, status=0, shop_id_id=1, user_id_id=4, address_id_id=4)
o.save()
d = datetime.now()
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,5), order_time=d, total_price=24, status=0, shop_id_id=1, user_id_id=5, address_id_id=5)
o.save()
d = datetime.now()
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,5), order_time=d, total_price=24, status=0, shop_id_id=1, user_id_id=5, address_id_id=5)
o.save()
d = datetime.now()-timedelta(hours=4)
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,5), order_time=d, total_price=24, status=2, shop_id_id=1, user_id_id=5, address_id_id=5)
o.save()
d = datetime.now()-timedelta(hours=3)
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,5), order_time=d, total_price=24, status=2, shop_id_id=1, user_id_id=5, address_id_id=5)
o.save()
d = datetime.now()-timedelta(hours=2)
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,5), order_time=d, total_price=24, status=2, shop_id_id=1, user_id_id=5, address_id_id=5)
o.save()
d = datetime.now()-timedelta(hours=1)
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,5), order_time=d, total_price=24, status=2, shop_id_id=1, user_id_id=5, address_id_id=5)
o.save()

d = datetime.now()-timedelta(minutes=4)
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,5), order_time=d, total_price=24, status=1, shop_id_id=1, user_id_id=5, address_id_id=5)
o.save()

d = datetime.now()-timedelta(minutes=3)
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,2), order_time=d, total_price=24, status=1, shop_id_id=1, user_id_id=2, address_id_id=2)
o.save()

d = datetime.now()-timedelta(minutes=2)
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,4), order_time=d, total_price=24, status=1, shop_id_id=1, user_id_id=4, address_id_id=4)
o.save()

d = datetime.now()-timedelta(minutes=2)
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,2), order_time=d, total_price=24, status=1, shop_id_id=1, user_id_id=2, address_id_id=2)
o.save()

d = datetime.now()-timedelta(minutes=1)
o = Orders(order_num = '{:%Y%m%d%H%M%S}{:d}'.format(d,5), order_time=d, total_price=24, status=1, shop_id_id=1, user_id_id=5, address_id_id=5)
o.save()