# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(max_length=15),
        ),
    ]
