# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20160928_1444'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diancan_user',
            table='diancan_user',
        ),
    ]
