# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20160928_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.RemoveField(
            model_name='diancan_user',
            name='user',
        ),
        migrations.DeleteModel(
            name='diancan_user',
        ),
    ]
