# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('consignee', models.CharField(max_length=20)),
                ('consignee_tel', models.CharField(max_length=15)),
                ('is_default', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
    ]
