# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20161005_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='consignee',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='consignee_tel',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=400),
        ),
    ]
